---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyPairName:
    Type: String

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0bba69335379e17f8
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get -y install awscli mysql-client
          aws s3 cp s3://s3-data-bucket-1122/sample-data.sql .
          mysql -h localhost -u root -pmypassword < sample-data.sql
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and MySQL access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
